use super::number::Number;
use serde::Serialize;

#[derive(Serialize)]
pub(super) struct CruiseState {
    pub frame: u64,
    pub v_cruise_kph: Number,
    pub v_cruise_cluster_kph: Number,
    pub v_cruise_kph_last: Number,
    pub _cruise_speed_initialized: bool,
    pub enabled_last: bool,
    pub long_pressed: bool,
    pub button_cnt: i64,
    pub button_prev: u16,
    pub button_long_time: i64,
    pub button_big_step: bool,
    pub is_metric: bool,
    pub v_ego_kph_set: f64,
    pub _cruise_speed_min: f64,
    pub _cruise_speed_max: f64,
    pub _cruise_speed_unit: i32,
    pub _cruise_speed_unit_basic: i32,
    pub _cruise_button_mode: i32,
    pub _cancel_button_mode: i32,
    pub _lfa_button_mode: i32,
    pub disengage_on_accelerator: bool,
    pub _gas_pressed_count: i64,
    pub _gas_pressed_count_last: i64,
    pub _gas_pressed_value: f64,
    pub _gas_tok_timer: i64,
    pub _gas_tok: bool,
    pub _brake_pressed_count: i64,
    pub _soft_hold_count: i64,
    pub _soft_hold_active: i16,
    pub soft_hold_on_cancel: bool,
    pub _cruise_ready: bool,
    pub _cruise_cancel_state: bool,
    pub _pause_auto_speed_up: bool,
    pub _activate_cruise: i16,
    pub _cruise_available: bool,
    pub _hold_interlock_active: bool,
    pub _steering_interlock_active: bool,
    pub _lat_enabled: bool,
    pub _v_cruise_kph_at_brake: Number,
    pub cruise_state_available_last: bool,
    pub _paddle_decel_active: bool,
    pub carrot_cruise_active: bool,
    #[serde(rename = "xState")]
    pub x_state: i32,
    #[serde(rename = "trafficState")]
    pub traffic_state: i32,
    #[serde(rename = "aTarget")]
    pub a_target: f64,
    #[serde(rename = "nRoadLimitSpeed")]
    pub n_road_limit_speed: f64,
    #[serde(rename = "desiredSpeed")]
    pub desired_speed: f64,
    pub road_limit_kph: f64,
    #[serde(rename = "nRoadLimitSpeed_last")]
    pub n_road_limit_speed_last: f64,
    pub carrot_cmd_index_last: i32,
    pub carrot_cmd_index: i32,
    pub carrot_cmd: String,
    pub carrot_arg: String,
    pub _cancel_timer: i64,
    pub d_rel: f64,
    pub v_rel: f64,
    pub v_lead_kph: f64,
    pub model_v_kph: f64,
    pub _log_timer: i64,
    pub _log_timeout: i64,
    pub log: String,
    #[serde(rename = "autoCruiseControl")]
    pub auto_cruise_control: f64,
    #[serde(rename = "autoCruiseControl_cancel_timer")]
    pub auto_cruise_control_cancel_timer: i64,
    #[serde(rename = "AutoSpeedUptoRoadSpeedLimit")]
    pub unused_auto_speed_upto_road_speed_limit: f64,
    #[serde(rename = "autoGasCancelSpeed")]
    pub auto_gas_cancel_speed: f64,
    #[serde(rename = "useLaneLineSpeed")]
    pub use_lane_line_speed: f64,
    #[serde(rename = "useLaneLineSpeedApply")]
    pub use_lane_line_speed_apply: f64,
    #[serde(rename = "autoGasTokSpeed")]
    pub auto_gas_tok_speed: f64,
    #[serde(rename = "autoGasSyncSpeed")]
    pub auto_gas_sync_speed: i32,
    #[serde(rename = "applyModelSpeed")]
    pub apply_model_speed: f64,
    #[serde(rename = "autoSpeedUptoRoadSpeedLimit")]
    pub auto_speed_upto_road_speed_limit: f64,
    #[serde(rename = "autoRoadSpeedAdjust")]
    pub auto_road_speed_adjust: f64,
    pub speed_from_pcm: i32,
    pub _cruise_button_long_delay: i32,
    pub _paddle_mode: i32,
    #[serde(rename = "autoRoadSpeedLimitOffset")]
    pub auto_road_speed_limit_offset: i32,
    #[serde(rename = "autoNaviSpeedSafetyFactor")]
    pub auto_navi_speed_safety_factor: f64,
    #[serde(rename = "cruiseOnDist")]
    pub cruise_on_dist: f64,
    pub _cruise_speed_table: [f64; 5],
}
impl CruiseState {
    pub fn new(auto_engage: i32, lane_speed: i32, disengage: bool, soft_hold: bool) -> Self {
        Self {
            frame: 0,
            v_cruise_kph: Number::int(20.),
            v_cruise_cluster_kph: Number::int(20.),
            v_cruise_kph_last: Number::int(20.),
            _cruise_speed_initialized: false,
            enabled_last: false,
            long_pressed: false,
            button_cnt: 0,
            button_prev: 0,
            button_long_time: 40,
            button_big_step: false,
            is_metric: true,
            v_ego_kph_set: 0.,
            _cruise_speed_min: 5.,
            _cruise_speed_max: 161.,
            _cruise_speed_unit: 10,
            _cruise_speed_unit_basic: 1,
            _cruise_button_mode: 2,
            _cancel_button_mode: 0,
            _lfa_button_mode: 0,
            disengage_on_accelerator: disengage,
            _gas_pressed_count: 0,
            _gas_pressed_count_last: 0,
            _gas_pressed_value: 0.,
            _gas_tok_timer: 40,
            _gas_tok: false,
            _brake_pressed_count: 0,
            _soft_hold_count: 0,
            _soft_hold_active: 0,
            soft_hold_on_cancel: soft_hold,
            _cruise_ready: false,
            _cruise_cancel_state: false,
            _pause_auto_speed_up: false,
            _activate_cruise: 0,
            _cruise_available: false,
            _hold_interlock_active: false,
            _steering_interlock_active: false,
            _lat_enabled: auto_engage > 0,
            _v_cruise_kph_at_brake: Number::int(0.),
            cruise_state_available_last: false,
            _paddle_decel_active: false,
            carrot_cruise_active: false,
            x_state: 0,
            traffic_state: 0,
            a_target: 0.,
            n_road_limit_speed: 30.,
            desired_speed: 250.,
            road_limit_kph: 30.,
            n_road_limit_speed_last: 30.,
            carrot_cmd_index_last: 0,
            carrot_cmd_index: 0,
            carrot_cmd: String::new(),
            carrot_arg: String::new(),
            _cancel_timer: 0,
            d_rel: 0.,
            v_rel: 0.,
            v_lead_kph: 0.,
            model_v_kph: 0.,
            _log_timer: 0,
            _log_timeout: 300,
            log: String::new(),
            auto_cruise_control: 0.,
            auto_cruise_control_cancel_timer: 0,
            unused_auto_speed_upto_road_speed_limit: 0.,
            auto_gas_cancel_speed: 30.,
            use_lane_line_speed: f64::from(lane_speed),
            use_lane_line_speed_apply: f64::from(lane_speed),
            auto_gas_tok_speed: 0.,
            auto_gas_sync_speed: 0,
            apply_model_speed: 0.,
            auto_speed_upto_road_speed_limit: 0.,
            auto_road_speed_adjust: 0.,
            speed_from_pcm: 0,
            _cruise_button_long_delay: 0,
            _paddle_mode: 0,
            auto_road_speed_limit_offset: 0,
            auto_navi_speed_safety_factor: 0.,
            cruise_on_dist: 0.,
            _cruise_speed_table: [0.; 5],
        }
    }
}
