pub struct Message {
    pub address: u32,
    pub candidates: &'static [&'static str],
    pub bus: u8,
    pub step: u64,
    pub data: &'static [u8],
}
pub const MESSAGES: &[Message] = &[
    Message {
        address: 296,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_AVALON",
        ],
        bus: 1,
        step: 3,
        data: &[244, 1, 144, 131, 0, 55],
    },
    Message {
        address: 296,
        candidates: &[
            "TOYOTA_HIGHLANDER",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
        ],
        bus: 1,
        step: 3,
        data: &[3, 0, 32, 0, 0, 82],
    },
    Message {
        address: 321,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_HIGHLANDER",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 1,
        step: 2,
        data: &[0, 0, 0, 70],
    },
    Message {
        address: 352,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_HIGHLANDER",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 1,
        step: 7,
        data: &[0, 0, 8, 18, 1, 49, 156, 81],
    },
    Message {
        address: 353,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_AVALON",
            "TOYOTA_PRIUS_V",
        ],
        bus: 1,
        step: 7,
        data: &[0, 30, 0, 0, 0, 128, 7],
    },
    Message {
        address: 353,
        candidates: &[
            "TOYOTA_HIGHLANDER",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
        ],
        bus: 1,
        step: 7,
        data: &[0, 30, 0, 212, 0, 0, 91],
    },
    Message {
        address: 643,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_HIGHLANDER",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 0,
        step: 3,
        data: &[0, 0, 0, 0, 0, 0, 140],
    },
    Message {
        address: 742,
        candidates: &["TOYOTA_PRIUS", "TOYOTA_RAV4H", "LEXUS_RX"],
        bus: 0,
        step: 3,
        data: &[255, 248, 0, 8, 127, 224, 0, 78],
    },
    Message {
        address: 743,
        candidates: &["TOYOTA_PRIUS", "TOYOTA_RAV4H", "LEXUS_RX"],
        bus: 0,
        step: 3,
        data: &[168, 156, 49, 156, 0, 0, 0, 2],
    },
    Message {
        address: 830,
        candidates: &["TOYOTA_PRIUS", "TOYOTA_RAV4H", "LEXUS_RX"],
        bus: 0,
        step: 20,
        data: &[15, 255, 38, 64, 0, 31, 0],
    },
    Message {
        address: 836,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_HIGHLANDER",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 0,
        step: 5,
        data: &[0, 0, 1, 0, 0, 0, 0, 80],
    },
    Message {
        address: 869,
        candidates: &["TOYOTA_PRIUS", "LEXUS_NX", "TOYOTA_HIGHLANDER"],
        bus: 0,
        step: 20,
        data: &[0, 0, 0, 128, 3, 0, 8],
    },
    Message {
        address: 869,
        candidates: &[
            "TOYOTA_RAV4",
            "TOYOTA_RAV4H",
            "TOYOTA_COROLLA",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "LEXUS_RX",
            "TOYOTA_PRIUS_V",
        ],
        bus: 0,
        step: 20,
        data: &[0, 0, 0, 128, 252, 0, 8],
    },
    Message {
        address: 870,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_HIGHLANDER",
        ],
        bus: 0,
        step: 20,
        data: &[0, 0, 77, 130, 64, 2, 0],
    },
    Message {
        address: 870,
        candidates: &[
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 0,
        step: 20,
        data: &[0, 114, 7, 255, 9, 254, 0],
    },
    Message {
        address: 1136,
        candidates: &["TOYOTA_PRIUS", "LEXUS_RX"],
        bus: 1,
        step: 100,
        data: &[0, 0, 2, 122],
    },
    Message {
        address: 1136,
        candidates: &[
            "TOYOTA_HIGHLANDER",
            "TOYOTA_RAV4H",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 1,
        step: 100,
        data: &[0, 0, 1, 121],
    },
    Message {
        address: 1227,
        candidates: &[
            "TOYOTA_PRIUS",
            "TOYOTA_RAV4H",
            "LEXUS_RX",
            "LEXUS_NX",
            "TOYOTA_RAV4",
            "TOYOTA_COROLLA",
            "TOYOTA_HIGHLANDER",
            "TOYOTA_AVALON",
            "TOYOTA_SIENNA",
            "LEXUS_CTH",
            "LEXUS_ES",
            "TOYOTA_PRIUS_V",
        ],
        bus: 0,
        step: 100,
        data: &[12, 0, 0, 0, 0, 0, 0, 0],
    },
];
