# /// script
# requires-python = ">=3.12"
# dependencies = ["pytest"]
# ///
# ─── How to run ───
# PYTHONPATH=rust/tools python3 -m pytest rust/tools/tests/test_card_assets.py
from pathlib import Path
import json

import pytest

from card_prepare_assets import GENERATED, digest, prepare_assets


def test_source_assets_are_preserved_and_generators_are_isolated(tmp_path: Path) -> None:
  # Given the pinned repository sources and a fresh package destination.
  repository = Path(__file__).resolve().parents[3]
  destination = tmp_path / "dbc"

  # When preparing the package without any previous oracle output.
  manifest = prepare_assets(repository, destination)

  # Then all source inputs remain unchanged, including checked-in generated DBCs.
  for name, checksum in manifest["source_sha256"].items():
    assert digest(repository / name) == checksum
  for original in (repository / "opendbc_repo/opendbc/dbc").glob("*.dbc"):
    if original.name not in GENERATED:
      assert (destination / original.name).read_bytes() == original.read_bytes()
      assert (destination / original.name).stat().st_ino != original.stat().st_ino
  for name in GENERATED:
    assert (destination / name).read_text().startswith('CM_ "AUTOGENERATED FILE, DO NOT EDIT";')
    assert 'CM_ "IMPORT ' not in (destination / name).read_text()
  assert json.loads((destination / "card-assets.json").read_text()) == manifest
  assert not list(destination.glob("*.py"))


def test_existing_package_is_never_overwritten(tmp_path: Path) -> None:
  # Given an existing destination with retained evidence.
  marker = tmp_path / "retained"
  marker.write_bytes(b"evidence")

  # When asking preparation to replace it.
  with pytest.raises(FileExistsError):
    prepare_assets(Path(__file__).resolve().parents[3], tmp_path)

  # Then the existing artifact is untouched.
  assert marker.read_bytes() == b"evidence"


def test_missing_generator_input_does_not_publish_partial_package(tmp_path: Path) -> None:
  # Given a source tree without its required generator.
  repository = tmp_path / "missing-source"
  repository.mkdir()
  destination = tmp_path / "dbc"

  # When preparing an invalid source tree.
  with pytest.raises(FileNotFoundError):
    prepare_assets(repository, destination)

  # Then no successful-looking package is published.
  assert not destination.exists()
