pub const SERVICES: &[Service] = &[
    Service {
        name: "gyroscope",
        should_log: true,
        frequency: 104.0,
        decimation: Some(104),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "accelerometer",
        should_log: true,
        frequency: 104.0,
        decimation: Some(104),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "magnetometer",
        should_log: true,
        frequency: 25.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "lightSensor",
        should_log: true,
        frequency: 100.0,
        decimation: Some(100),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "temperatureSensor",
        should_log: true,
        frequency: 2.0,
        decimation: Some(200),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "gpsNMEA",
        should_log: true,
        frequency: 9.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "deviceState",
        should_log: true,
        frequency: 2.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "touch",
        should_log: true,
        frequency: 20.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "can",
        should_log: true,
        frequency: 100.0,
        decimation: Some(2053),
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "controlsState",
        should_log: true,
        frequency: 100.0,
        decimation: Some(10),
        queue_size: 2097152,
        frequency_range: None,
    },
    Service {
        name: "selfdriveState",
        should_log: true,
        frequency: 100.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "pandaStates",
        should_log: true,
        frequency: 10.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "peripheralState",
        should_log: true,
        frequency: 2.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "radarState",
        should_log: true,
        frequency: 20.0,
        decimation: Some(5),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "roadEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "liveTracks",
        should_log: true,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: Some((14.0, 25.0)),
    },
    Service {
        name: "sendcan",
        should_log: true,
        frequency: 100.0,
        decimation: Some(139),
        queue_size: 2097152,
        frequency_range: None,
    },
    Service {
        name: "logMessage",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "errorLogMessage",
        should_log: true,
        frequency: 0.0,
        decimation: Some(1),
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "liveCalibration",
        should_log: true,
        frequency: 4.0,
        decimation: Some(4),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "liveTorqueParameters",
        should_log: true,
        frequency: 4.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "liveDelay",
        should_log: true,
        frequency: 4.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "androidLog",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "carState",
        should_log: true,
        frequency: 100.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "carControl",
        should_log: true,
        frequency: 100.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "carOutput",
        should_log: true,
        frequency: 100.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "longitudinalPlan",
        should_log: true,
        frequency: 20.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: Some((14.0, 25.0)),
    },
    Service {
        name: "lateralManeuverPlan",
        should_log: true,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "driverAssistance",
        should_log: true,
        frequency: 20.0,
        decimation: Some(20),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "procLog",
        should_log: true,
        frequency: 0.5,
        decimation: Some(15),
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "gpsLocationExternal",
        should_log: true,
        frequency: 10.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "gpsLocation",
        should_log: true,
        frequency: 1.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "ubloxGnss",
        should_log: true,
        frequency: 10.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "qcomGnss",
        should_log: true,
        frequency: 2.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "gnssMeasurements",
        should_log: true,
        frequency: 10.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "clocks",
        should_log: true,
        frequency: 0.1,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "ubloxRaw",
        should_log: true,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "livePose",
        should_log: true,
        frequency: 20.0,
        decimation: Some(4),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "liveParameters",
        should_log: true,
        frequency: 20.0,
        decimation: Some(5),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "cameraOdometry",
        should_log: true,
        frequency: 20.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "thumbnail",
        should_log: true,
        frequency: 0.016666666666666666,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "lateralPlan",
        should_log: true,
        frequency: 20.0,
        decimation: Some(5),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "onroadEvents",
        should_log: true,
        frequency: 1.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "carParams",
        should_log: true,
        frequency: 0.02,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "roadCameraState",
        should_log: true,
        frequency: 20.0,
        decimation: Some(20),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "driverCameraState",
        should_log: true,
        frequency: 20.0,
        decimation: Some(20),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "driverEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "driverStateV2",
        should_log: true,
        frequency: 20.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "driverMonitoringState",
        should_log: true,
        frequency: 20.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "wideRoadEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "wideRoadCameraState",
        should_log: true,
        frequency: 20.0,
        decimation: Some(20),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "drivingModelData",
        should_log: true,
        frequency: 20.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "modelV2",
        should_log: true,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "managerState",
        should_log: true,
        frequency: 2.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "uploaderState",
        should_log: true,
        frequency: 0.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "navInstruction",
        should_log: true,
        frequency: 1.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "navRoute",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "navRouteNavd",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "navThumbnail",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "navModel",
        should_log: true,
        frequency: 2.0,
        decimation: Some(4),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "mapRenderState",
        should_log: true,
        frequency: 2.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "qRoadEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "userBookmark",
        should_log: true,
        frequency: 0.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "soundPressure",
        should_log: true,
        frequency: 10.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "rawAudioData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "bookmarkButton",
        should_log: true,
        frequency: 0.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "audioFeedback",
        should_log: true,
        frequency: 0.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "roadEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "driverEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "wideRoadEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "qRoadEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "carrotMan",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "navInstructionCarrot",
        should_log: true,
        frequency: 1.0,
        decimation: Some(10),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "carrotNavi",
        should_log: true,
        frequency: 2.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "carrotNaviMedia",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "uiDebug",
        should_log: true,
        frequency: 0.0,
        decimation: Some(1),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "testJoystick",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "alertDebug",
        should_log: true,
        frequency: 20.0,
        decimation: Some(5),
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "livestreamWideRoadEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "livestreamRoadEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "livestreamDriverEncodeIdx",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "livestreamWideRoadEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 2097152,
        frequency_range: None,
    },
    Service {
        name: "livestreamRoadEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 2097152,
        frequency_range: None,
    },
    Service {
        name: "livestreamDriverEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 2097152,
        frequency_range: None,
    },
    Service {
        name: "youtubeRoadEncodeData",
        should_log: false,
        frequency: 20.0,
        decimation: None,
        queue_size: 10485760,
        frequency_range: None,
    },
    Service {
        name: "customReservedRawData0",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "customReservedRawData1",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
    Service {
        name: "customReservedRawData2",
        should_log: true,
        frequency: 0.0,
        decimation: None,
        queue_size: 256000,
        frequency_range: None,
    },
];
