"""Emit Rust constant tables from the unchanged original sensor constructors."""

import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
from typing import cast


FLOAT_FIELDS = {
  "pixel_size_mm",
  "dc_gain_factor",
  "dc_gain_on_grey",
  "dc_gain_off_grey",
  "ev_scale",
  "analog_gain_cost_low",
  "analog_gain_cost_high",
  "target_grey_factor",
  "min_ev",
  "max_ev",
}


def float_literal(value: float) -> str:
  bits = struct.unpack("<I", struct.pack("<f", value))[0]
  return f"f32::from_bits(0x{bits:08x})"


def main() -> None:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--source", type=Path, required=True)
  parser.add_argument("--reference", type=Path, required=True)
  args = parser.parse_args()
  source = cast(Path, args.source)
  reference = cast(Path, args.reference)
  result = subprocess.run([str(reference)], input="config 1\nconfig 2\nconfig 3\n", text=True, capture_output=True, check=True)
  configurations = [cast(dict[str, int | float | bool | list[int | float] | list[list[int]]], json.loads(line)) for line in result.stdout.splitlines()]
  print("// Generated by rust/tools/generate_camerad_sensor_data.py. Original MIT license applies.")
  print("// Pure constant sensor data; no runtime C++ dependency.")
  for path in sorted((source / "openpilot/system/camerad/sensors").glob("*")):
    if path.suffix in {".cc", ".h"}:
      print(f"// {path.name} SHA-256 {hashlib.sha256(path.read_bytes()).hexdigest()}")
  print("use super::{Register, SensorConfig};\n")
  for kind, (name, config) in enumerate(zip(("AR0231", "OX03C10", "OS04C10"), configurations, strict=True), 1):
    print(f"pub static {name}: SensorConfig = SensorConfig {{")
    for key, value in config.items():
      if key in FLOAT_FIELDS:
        literal = float_literal(cast(float, value))
      elif key == "data_word":
        literal = "true" if value else "false"
      elif key in {"start_reg_array", "init_reg_array"}:
        pairs = cast(list[list[int]], value)
        literal = "&[" + ", ".join(f"Register({pair[0]}, {pair[1]})" for pair in pairs) + "]"
      elif key == "sensor_analog_gains":
        literal = "&[" + ", ".join(float_literal(item) for item in cast(list[float], value)) + "]"
      elif key in {"color_correct_matrix", "gamma_lut_rgb", "linearization_lut", "linearization_pts", "vignetting_lut"}:
        literal = "&[" + ", ".join(str(item) for item in cast(list[int], value)) + "]"
      else:
        literal = str(value)
      print(f"    {key}: {literal},")
    print("};\n")
    if kind > 1:
      count = cast(int, config["analog_gain_max_idx"]) + 1
      requests = "".join(f"exposure {kind} 5 {gain} 0\n" for gain in range(count))
      result = subprocess.run([str(reference)], input=requests, text=True, capture_output=True, check=True)
      registers = []
      for line in result.stdout.splitlines():
        data = dict(cast(list[list[int]], json.loads(line)))
        registers.append(data[0x3508] << 8 | data[0x3509])
      print(f"pub const {name}_GAIN_REGISTERS: [u32; {count}] = {registers};\n")


if __name__ == "__main__":
  main()
