#!/usr/bin/env python3
"""Generate typed Rust field readers from the unchanged binary schemas; build-time only."""

from pathlib import Path
import ast

from openpilot.system.ubloxd import binary_struct as bs
from openpilot.system.ubloxd.ubx import Ubx
from openpilot.system.ubloxd.gps import Gps
from openpilot.system.ubloxd.glonass import Glonass


def render(name, schema):
  fields, reads = [], []
  for field, annotation in schema.__binary_fields__:
    kind = bs._field_type_from_spec(annotation)
    if isinstance(kind, bs.EnumType):
      kind = kind.base_type
    if isinstance(kind, bs.IntType):
      typ = ('i' if kind.signed else 'u') + str(kind.bits)
      method = typ + ('be' if kind.big_endian else '')
      read = f'cursor.{method}()?'
    elif isinstance(kind, bs.FloatType):
      typ = 'f' + str(kind.bits)
      read = f'cursor.{typ}()?'
    elif isinstance(kind, bs.BitsType):
      typ = 'bool' if kind.bits == 1 else ('u32' if kind.bits <= 32 else 'u64')
      read = f'cursor.bits({kind.bits})?'
      if kind.bits == 1:
        read += ' != 0'
      elif kind.bits <= 32:
        read = f'u32::try_from({read}).map_err(|_| Error::Malformed("bit width"))?'
    elif isinstance(kind, bs.BytesType):
      reads.append(f'        cursor.skip({kind.size})?;')
      continue
    elif isinstance(kind, bs.ArrayType):
      continue
    else:
      raise TypeError(f'unsupported schema field {name}.{field}: {kind}')
    fields.append(f'    pub {field}: {typ},')
    reads.append(f'        let {field} = {read};')
  names = [line.split()[1].removesuffix(':') for line in fields]
  return '\n'.join(
    [
      '#[derive(Clone, Debug)]',
      f'pub struct {name} {{',
      *fields,
      '}',
      f'impl {name} {{',
      '    pub fn read(cursor: &mut Cursor<\'_>) -> Result<Self, Error> {',
      *reads,
      '        Ok(Self { ' + ', '.join(names) + ' })',
      '    }',
      '}',
      '',
    ]
  )


def main():
  root = Path(__file__).resolve().parents[1] / 'crates/ublox/src/layouts'
  groups = {
    'nav': [('NavPvt', Ubx.NavPvt), ('NavSat', Ubx.NavSat), ('Satellite', Ubx.NavSat.Nav)],
    'raw': [('Rawx', Ubx.RxmRawx), ('Measurement', Ubx.RxmRawx.Measurement)],
    'hardware': [('MonHw', Ubx.MonHw), ('MonHw2', Ubx.MonHw2)],
    'gps': [('How', Gps.How), ('Subframe1', Gps.Subframe1), ('Subframe2', Gps.Subframe2), ('Subframe3', Gps.Subframe3)],
    'glonass': [(f'String{i}', getattr(Glonass, f'String{i}')) for i in range(1, 6)],
  }
  for module, schemas in groups.items():
    text = '// Generated by rust/tools/generate_ublox_layouts.py from unchanged system/ubloxd schemas.\n'
    text += '// Field tables retain source signedness and alignment, including unused parsed fields.\n'
    text += 'use crate::{binary::Cursor, Error};\n'
    text += ''.join(render(name, schema) for name, schema in schemas)
    (root / f'{module}.rs').write_text(text)
  (root / 'mod.rs').write_text('pub mod nav;\npub mod raw;\npub mod hardware;\npub mod gps;\npub mod glonass;\n')
  source = ast.parse((Path(__file__).resolve().parents[2] / 'openpilot/system/ubloxd/pigeond.py').read_text())
  output = ['// Exact source receiver command bytes; generated by generate_ublox_layouts.py.']

  def literal(value):
    return '&[' + ', '.join(f'0x{byte:02x}' for byte in value) + ']'

  for node in source.body:
    if isinstance(node, ast.Assign) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, bytes):
      output.append(f'pub const {node.targets[0].id}: &[u8] = {literal(node.value.value)};')
  for name, function, method in [
    ('CONFIG_COMMANDS', 'init_pigeon', 'send_with_ack'),
    ('BAUD', 'init_baudrate', 'send'),
    ('SAVE', 'save_almanac', 'send'),
    ('STOP', 'deinitialize_and_exit', 'send'),
    ('RESTORE', 'init_pigeon', 'send'),
  ]:
    node = next(node for node in source.body if isinstance(node, ast.FunctionDef) and node.name == function)
    values = [
      call.args[0].value
      for call in ast.walk(node)
      if isinstance(call, ast.Call)
      and isinstance(call.func, ast.Attribute)
      and call.func.attr == method
      and call.args
      and isinstance(call.args[0], ast.Constant)
      and isinstance(call.args[0].value, bytes)
    ]
    if name == 'CONFIG_COMMANDS':
      output.append('pub const CONFIG_COMMANDS: &[&[u8]] = &[' + ', '.join(literal(value) for value in values) + '];')
    else:
      assert len(values) == 1
      output.append(f'pub const {name}: &[u8] = {literal(values[0])};')
  cls = next(node for node in source.body if isinstance(node, ast.ClassDef) and node.name == 'TTYPigeon')
  reset = next(node for node in cls.body if isinstance(node, ast.FunctionDef) and node.name == 'reset_device')
  values = [
    call.args[0].value
    for call in ast.walk(reset)
    if isinstance(call, ast.Call)
    and isinstance(call.func, ast.Attribute)
    and call.func.attr in ('send', 'send_with_ack')
    and call.args
    and isinstance(call.args[0], ast.Constant)
    and isinstance(call.args[0].value, bytes)
  ]
  for name, value in zip(('COLD_START', 'CLEAR_CONFIG', 'CLEAR_BACKUP', 'RESET_RESTORE'), values, strict=True):
    output.append(f'pub const {name}: &[u8] = {literal(value)};')
  (root.parent / 'commands.rs').write_text('\n'.join(output) + '\n')


if __name__ == '__main__':
  main()
