import unicodedata


def main() -> None:
  assert unicodedata.unidata_version == '15.0.0'
  ranges = []
  start = end = None
  decimal = []
  for point in range(0x110000):
    if chr(point).isdigit():
      if start is None:
        start = point
      end = point
    elif start is not None:
      ranges.append((start, end))
      start = end = None
    if unicodedata.decimal(chr(point), None) == 0:
      assert all(unicodedata.decimal(chr(point + value), None) == value for value in range(10))
      decimal.append(point)
  assert start is None
  print('// Generated by rust/tools/generate_bluetooth_digits.py from CPython Unicode 15.0.0.')
  print('pub(super) const DIGITS: &[(u32, u32)] = &[')
  for low, high in ranges:
    print(f'    (0x{low:x}, 0x{high:x}),')
  print('];\n')
  print('pub(super) const DECIMAL: &[u32] = &[')
  for start in range(0, len(decimal), 8):
    print('    ' + ', '.join(f'0x{point:x}' for point in decimal[start:start + 8]) + ',')
  print('];')


if __name__ == '__main__':
  main()
