"""Capture observable state from unchanged original planner owners."""

import numpy as np


def frame(long, lat, carrot, logs, operations):
  mpc = long.mpc
  long_warning = next((int(args[0].rsplit(': ', 1)[1]) for level, args, _ in logs if level == 'warning' and args[0].startswith('Long mpc reset')), None)
  lat_warning = any(level == 'warning' and args[0] == 'Lateral mpc - nan: True' for level, args, _ in logs)
  lane = lat.LP
  debug = f"{'lanemode' if lat.lanelines_active else 'laneless'} | {lane.lane_width_left:.1f}m | {lane.lane_width:.1f}m | {lane.lane_width_right:.1f}m | " + (
    f'offset={lane.offset_total * 100.0:.1f}cm turn={np.clip(lat.curve_speed, -200, 200):.0f}km/h' if lat.lanelines_active else ''
  )
  output = {
    'path_points': lat.y_pts.tolist(),
    'headings': lat.lat_mpc.x_sol[:17, 2].tolist(),
    'distances': lat.lat_mpc.x_sol[:17, 0].tolist(),
    'curvatures': (lat.lat_mpc.x_sol[:17, 3] / np.maximum(lat.v_plan[:17], 6.0)).tolist(),
    'curvature_rates': [float(x.item() / max(lat.v_ego, 6.0)) for x in lat.lat_mpc.u_sol[:16]] + [0.0],
    'solution_valid': bool(lat.solution_invalid_cnt < 2),
    'use_lane_lines': bool(lat.lanelines_active),
    'lane_width': float(lane.lane_width),
    'position': [lat.x_sol[:, 0].tolist(), lat.x_sol[:, 1].tolist(), lat.path_xyz[:, 2].tolist()],
    'debug_text': debug,
  }
  return {
    'parameters': operations.copy(),
    'long_warning': long_warning,
    'lat_warning': lat_warning,
    'long': {
      'fcw': bool(long.fcw),
      'a_target': float(long.output_a_target),
      'a_base': float(long.output_a_target_base),
      'v_target': float(long.output_v_target_now),
      'j_target': float(long.output_j_target_now),
      'should_stop': bool(long.output_should_stop),
      'preview': float(long.lead_preview),
      'preview_time': float(long.lead_preview_action_time),
      'preview_accel': float(long.lead_preview_accel),
      'tracks': long.lead_track_frames.copy(),
      'speed': long.v_desired_trajectory.tolist(),
      'accel': long.a_desired_trajectory.tolist(),
      'jerk': long.j_desired_trajectory.tolist(),
      'cruise': float(long.v_cruise_kph),
      'coast': float(long.coasting_target),
      'coast_percent': long.coasting_percent,
      'desired_accel': float(long.a_desired),
      'cluster_ratio': float(long.vCluRatio),
    },
    'mpc': {
      'mode': mpc.mode,
      'source': mpc.source,
      'x': mpc.x_sol.tolist(),
      'u': mpc.u_sol.tolist(),
      'p': mpc.params.tolist(),
      'yref': mpc.yref.tolist(),
      'initial': mpc.x0.tolist(),
      'prev_a': mpc.prev_a.tolist(),
      'tf': float(mpc.t_follow),
      'distance': float(mpc.desired_distance),
      'base_distances': mpc.base_desired_distances.tolist(),
      'danger_factor': float(mpc.lead_danger_factor),
      'danger_margin': float(mpc.predicted_danger_margin),
      'change_cost': float(mpc.a_change_cost),
      'jerk_factor': float(mpc.jerk_cost_factor),
      'response_active': bool(mpc.lead_accel_response_active),
      'response_level': mpc.lead_accel_response_level,
      'gap_margins': mpc.lead_gap_margins.tolist(),
      'status': bool(mpc.status),
      'crash_count': int(mpc.crash_cnt),
      'solution_status': mpc.solution_status,
    },
    'carrot': {
      'frame': carrot.frame,
      'mode': carrot.mode,
      'driving_mode': carrot.myDrivingMode.value,
      'safe': float(carrot.mySafeFactor),
      'tf_factor': float(carrot.myTFollowFactor),
      'lead_response': carrot.leadAccelResponse,
      'traffic': carrot.trafficState.name,
      'state': carrot.xState.name,
      'fake_cruise_distance': float(carrot.fakeCruiseDistance),
      'x_stop': float(carrot.xStop),
      'actual_stop_distance': float(carrot.actual_stop_distance),
      'user_stop_distance': float(carrot.user_stop_distance),
      'brake': float(carrot.comfort_brake),
      'soft_hold': carrot.soft_hold_active,
      'lane_active': bool(carrot.lane_change_active),
      'desire': float(carrot.desireState),
      'desire_count': carrot.desireStateCount,
      'active': carrot.activeCarrot,
      'turn_distance': float(carrot.xDistToTurn),
      'atc_type': carrot.atcType,
      'atc_active': bool(carrot.atc_active),
      'eco_target': float(carrot.eco_target_speed),
      'stop_offset': float(carrot.trafficStopModelLeadOffset),
      'events': carrot.events.names,
      'cruise': float(carrot.v_cruise),
      'stop': float(carrot.stop_dist),
      'tf': float(carrot.t_follow_last),
      'jerk_factor': float(carrot.jerk_factor),
      'decel_extra': float(carrot._tf_decel_extra),
    },
    'lat': {
      'output': output,
      'x': lat.lat_mpc.x_sol.tolist(),
      'u': lat.lat_mpc.u_sol.tolist(),
      'initial': lat.x0.tolist(),
      'status': lat.lat_mpc.solution_status,
      'cost': float(lat.lat_mpc.cost),
      'invalid': lat.solution_invalid_cnt,
      'path': lat.path_xyz.tolist(),
      'speeds': lat.v_plan.tolist(),
      'yaw': lat.plan_yaw.astype(float).tolist(),
      'yaw_rate': lat.plan_yaw_rate.astype(float).tolist(),
    },
  }
