use super::points::ScreenPoint;
use serde::Serialize;
#[derive(Serialize)]
pub struct Carrot {
    pub mode: i32,
    pub color: i32,
    pub width: f64,
    pub active_lane: bool,
    pub long_active: bool,
    pub lane_speed: i32,
    pub sequence: f64,
    pub sequence_second: Option<i32>,
    pub position_t: f64,
    pub path_x: i32,
    pub path_y: i32,
    pub path_width: i32,
    pub filtered_x: f64,
    pub filtered_y: f64,
    pub filtered_width: f64,
    pub track_id: i32,
    pub lead_status: bool,
    pub radar_distance: f64,
    pub vision_distance: f64,
    pub x_state: i32,
    pub traffic_state: i32,
    pub speed: f64,
    pub brake_hold: bool,
    pub soft_hold: i16,
    pub cruise: i16,
    pub t_follow: f64,
    pub follow_distance: f64,
    pub follow_left: Option<ScreenPoint>,
    pub follow_right: Option<ScreenPoint>,
    pub lead_two_status: i32,
    pub lead_two_left: f64,
    pub lead_two_right: f64,
    pub lead_two_y: f64,
    pub barriers: [Vec<openpilot_ui_framework::geometry::Point>; 2],
}
impl Default for Carrot {
    fn default() -> Self {
        Self {
            mode: 13,
            color: 14,
            width: 1.,
            active_lane: false,
            long_active: false,
            lane_speed: 0,
            sequence: 0.,
            sequence_second: None,
            position_t: 0.,
            path_x: 0,
            path_y: 0,
            path_width: 120,
            filtered_x: 0.,
            filtered_y: 0.,
            filtered_width: 120.,
            track_id: -1,
            lead_status: false,
            radar_distance: 0.,
            vision_distance: 0.,
            x_state: 0,
            traffic_state: 0,
            speed: 0.,
            brake_hold: false,
            soft_hold: 0,
            cruise: 0,
            t_follow: 0.,
            follow_distance: 0.,
            follow_left: None,
            follow_right: None,
            lead_two_status: 0,
            lead_two_left: 0.,
            lead_two_right: 0.,
            lead_two_y: 0.,
            barriers: std::array::from_fn(|_| Vec::new()),
        }
    }
}
