// Generated by rust/tools/generate_ublox_layouts.py from unchanged system/ubloxd schemas.
// Field tables retain source signedness and alignment, including unused parsed fields.
use crate::{binary::Cursor, Error};
#[derive(Clone, Debug)]
pub struct String1 {
    pub not_used: u32,
    pub p1: u32,
    pub t_k: u32,
    pub x_vel_sign: bool,
    pub x_vel_value: u32,
    pub x_accel_sign: bool,
    pub x_accel_value: u32,
    pub x_sign: bool,
    pub x_value: u32,
}
impl String1 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let not_used = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        let p1 = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        let t_k = u32::try_from(cursor.bits(12)?).map_err(|_| Error::Malformed("bit width"))?;
        let x_vel_sign = cursor.bits(1)? != 0;
        let x_vel_value =
            u32::try_from(cursor.bits(23)?).map_err(|_| Error::Malformed("bit width"))?;
        let x_accel_sign = cursor.bits(1)? != 0;
        let x_accel_value =
            u32::try_from(cursor.bits(4)?).map_err(|_| Error::Malformed("bit width"))?;
        let x_sign = cursor.bits(1)? != 0;
        let x_value = u32::try_from(cursor.bits(26)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            not_used,
            p1,
            t_k,
            x_vel_sign,
            x_vel_value,
            x_accel_sign,
            x_accel_value,
            x_sign,
            x_value,
        })
    }
}
#[derive(Clone, Debug)]
pub struct String2 {
    pub b_n: u32,
    pub p2: bool,
    pub t_b: u32,
    pub not_used: u32,
    pub y_vel_sign: bool,
    pub y_vel_value: u32,
    pub y_accel_sign: bool,
    pub y_accel_value: u32,
    pub y_sign: bool,
    pub y_value: u32,
}
impl String2 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let b_n = u32::try_from(cursor.bits(3)?).map_err(|_| Error::Malformed("bit width"))?;
        let p2 = cursor.bits(1)? != 0;
        let t_b = u32::try_from(cursor.bits(7)?).map_err(|_| Error::Malformed("bit width"))?;
        let not_used = u32::try_from(cursor.bits(5)?).map_err(|_| Error::Malformed("bit width"))?;
        let y_vel_sign = cursor.bits(1)? != 0;
        let y_vel_value =
            u32::try_from(cursor.bits(23)?).map_err(|_| Error::Malformed("bit width"))?;
        let y_accel_sign = cursor.bits(1)? != 0;
        let y_accel_value =
            u32::try_from(cursor.bits(4)?).map_err(|_| Error::Malformed("bit width"))?;
        let y_sign = cursor.bits(1)? != 0;
        let y_value = u32::try_from(cursor.bits(26)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            b_n,
            p2,
            t_b,
            not_used,
            y_vel_sign,
            y_vel_value,
            y_accel_sign,
            y_accel_value,
            y_sign,
            y_value,
        })
    }
}
#[derive(Clone, Debug)]
pub struct String3 {
    pub p3: bool,
    pub gamma_n_sign: bool,
    pub gamma_n_value: u32,
    pub not_used: bool,
    pub p: u32,
    pub l_n: bool,
    pub z_vel_sign: bool,
    pub z_vel_value: u32,
    pub z_accel_sign: bool,
    pub z_accel_value: u32,
    pub z_sign: bool,
    pub z_value: u32,
}
impl String3 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let p3 = cursor.bits(1)? != 0;
        let gamma_n_sign = cursor.bits(1)? != 0;
        let gamma_n_value =
            u32::try_from(cursor.bits(10)?).map_err(|_| Error::Malformed("bit width"))?;
        let not_used = cursor.bits(1)? != 0;
        let p = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        let l_n = cursor.bits(1)? != 0;
        let z_vel_sign = cursor.bits(1)? != 0;
        let z_vel_value =
            u32::try_from(cursor.bits(23)?).map_err(|_| Error::Malformed("bit width"))?;
        let z_accel_sign = cursor.bits(1)? != 0;
        let z_accel_value =
            u32::try_from(cursor.bits(4)?).map_err(|_| Error::Malformed("bit width"))?;
        let z_sign = cursor.bits(1)? != 0;
        let z_value = u32::try_from(cursor.bits(26)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            p3,
            gamma_n_sign,
            gamma_n_value,
            not_used,
            p,
            l_n,
            z_vel_sign,
            z_vel_value,
            z_accel_sign,
            z_accel_value,
            z_sign,
            z_value,
        })
    }
}
#[derive(Clone, Debug)]
pub struct String4 {
    pub tau_n_sign: bool,
    pub tau_n_value: u32,
    pub delta_tau_n_sign: bool,
    pub delta_tau_n_value: u32,
    pub e_n: u32,
    pub not_used_1: u32,
    pub p4: bool,
    pub f_t: u32,
    pub not_used_2: u32,
    pub n_t: u32,
    pub n: u32,
    pub m: u32,
}
impl String4 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let tau_n_sign = cursor.bits(1)? != 0;
        let tau_n_value =
            u32::try_from(cursor.bits(21)?).map_err(|_| Error::Malformed("bit width"))?;
        let delta_tau_n_sign = cursor.bits(1)? != 0;
        let delta_tau_n_value =
            u32::try_from(cursor.bits(4)?).map_err(|_| Error::Malformed("bit width"))?;
        let e_n = u32::try_from(cursor.bits(5)?).map_err(|_| Error::Malformed("bit width"))?;
        let not_used_1 =
            u32::try_from(cursor.bits(14)?).map_err(|_| Error::Malformed("bit width"))?;
        let p4 = cursor.bits(1)? != 0;
        let f_t = u32::try_from(cursor.bits(4)?).map_err(|_| Error::Malformed("bit width"))?;
        let not_used_2 =
            u32::try_from(cursor.bits(3)?).map_err(|_| Error::Malformed("bit width"))?;
        let n_t = u32::try_from(cursor.bits(11)?).map_err(|_| Error::Malformed("bit width"))?;
        let n = u32::try_from(cursor.bits(5)?).map_err(|_| Error::Malformed("bit width"))?;
        let m = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            tau_n_sign,
            tau_n_value,
            delta_tau_n_sign,
            delta_tau_n_value,
            e_n,
            not_used_1,
            p4,
            f_t,
            not_used_2,
            n_t,
            n,
            m,
        })
    }
}
#[derive(Clone, Debug)]
pub struct String5 {
    pub n_a: u32,
    pub tau_c: u32,
    pub not_used: bool,
    pub n_4: u32,
    pub tau_gps: u32,
    pub l_n: bool,
}
impl String5 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let n_a = u32::try_from(cursor.bits(11)?).map_err(|_| Error::Malformed("bit width"))?;
        let tau_c = u32::try_from(cursor.bits(32)?).map_err(|_| Error::Malformed("bit width"))?;
        let not_used = cursor.bits(1)? != 0;
        let n_4 = u32::try_from(cursor.bits(5)?).map_err(|_| Error::Malformed("bit width"))?;
        let tau_gps = u32::try_from(cursor.bits(22)?).map_err(|_| Error::Malformed("bit width"))?;
        let l_n = cursor.bits(1)? != 0;
        Ok(Self {
            n_a,
            tau_c,
            not_used,
            n_4,
            tau_gps,
            l_n,
        })
    }
}
