// Generated by rust/tools/generate_ublox_layouts.py from unchanged system/ubloxd schemas.
// Field tables retain source signedness and alignment, including unused parsed fields.
use crate::{binary::Cursor, Error};
#[derive(Clone, Debug)]
pub struct How {
    pub tow_count: u32,
    pub alert: bool,
    pub anti_spoof: bool,
    pub subframe_id: u32,
    pub reserved: u32,
}
impl How {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let tow_count =
            u32::try_from(cursor.bits(17)?).map_err(|_| Error::Malformed("bit width"))?;
        let alert = cursor.bits(1)? != 0;
        let anti_spoof = cursor.bits(1)? != 0;
        let subframe_id =
            u32::try_from(cursor.bits(3)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            tow_count,
            alert,
            anti_spoof,
            subframe_id,
            reserved,
        })
    }
}
#[derive(Clone, Debug)]
pub struct Subframe1 {
    pub week_no: u32,
    pub code: u32,
    pub sv_accuracy: u32,
    pub sv_health: u32,
    pub iodc_msb: u32,
    pub l2_p_data_flag: bool,
    pub reserved1: u32,
    pub reserved2: u32,
    pub reserved3: u32,
    pub reserved4: u32,
    pub t_gd: i8,
    pub iodc_lsb: u8,
    pub t_oc: u16,
    pub af_2: i8,
    pub af_1: i16,
    pub af_0_sign: bool,
    pub af_0_value: u32,
    pub reserved5: u32,
}
impl Subframe1 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let week_no = u32::try_from(cursor.bits(10)?).map_err(|_| Error::Malformed("bit width"))?;
        let code = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        let sv_accuracy =
            u32::try_from(cursor.bits(4)?).map_err(|_| Error::Malformed("bit width"))?;
        let sv_health =
            u32::try_from(cursor.bits(6)?).map_err(|_| Error::Malformed("bit width"))?;
        let iodc_msb = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        let l2_p_data_flag = cursor.bits(1)? != 0;
        let reserved1 =
            u32::try_from(cursor.bits(23)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved2 =
            u32::try_from(cursor.bits(24)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved3 =
            u32::try_from(cursor.bits(24)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved4 =
            u32::try_from(cursor.bits(16)?).map_err(|_| Error::Malformed("bit width"))?;
        let t_gd = cursor.i8()?;
        let iodc_lsb = cursor.u8()?;
        let t_oc = cursor.u16be()?;
        let af_2 = cursor.i8()?;
        let af_1 = cursor.i16be()?;
        let af_0_sign = cursor.bits(1)? != 0;
        let af_0_value =
            u32::try_from(cursor.bits(21)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved5 =
            u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            week_no,
            code,
            sv_accuracy,
            sv_health,
            iodc_msb,
            l2_p_data_flag,
            reserved1,
            reserved2,
            reserved3,
            reserved4,
            t_gd,
            iodc_lsb,
            t_oc,
            af_2,
            af_1,
            af_0_sign,
            af_0_value,
            reserved5,
        })
    }
}
#[derive(Clone, Debug)]
pub struct Subframe2 {
    pub iode: u8,
    pub c_rs: i16,
    pub delta_n: i16,
    pub m_0: i32,
    pub c_uc: i16,
    pub e: i32,
    pub c_us: i16,
    pub sqrt_a: u32,
    pub t_oe: u16,
    pub fit_interval_flag: bool,
    pub aoda: u32,
    pub reserved: u32,
}
impl Subframe2 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let iode = cursor.u8()?;
        let c_rs = cursor.i16be()?;
        let delta_n = cursor.i16be()?;
        let m_0 = cursor.i32be()?;
        let c_uc = cursor.i16be()?;
        let e = cursor.i32be()?;
        let c_us = cursor.i16be()?;
        let sqrt_a = cursor.u32be()?;
        let t_oe = cursor.u16be()?;
        let fit_interval_flag = cursor.bits(1)? != 0;
        let aoda = u32::try_from(cursor.bits(5)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            iode,
            c_rs,
            delta_n,
            m_0,
            c_uc,
            e,
            c_us,
            sqrt_a,
            t_oe,
            fit_interval_flag,
            aoda,
            reserved,
        })
    }
}
#[derive(Clone, Debug)]
pub struct Subframe3 {
    pub c_ic: i16,
    pub omega_0: i32,
    pub c_is: i16,
    pub i_0: i32,
    pub c_rc: i16,
    pub omega: i32,
    pub omega_dot_sign: bool,
    pub omega_dot_value: u32,
    pub iode: u8,
    pub idot_sign: bool,
    pub idot_value: u32,
    pub reserved: u32,
}
impl Subframe3 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let c_ic = cursor.i16be()?;
        let omega_0 = cursor.i32be()?;
        let c_is = cursor.i16be()?;
        let i_0 = cursor.i32be()?;
        let c_rc = cursor.i16be()?;
        let omega = cursor.i32be()?;
        let omega_dot_sign = cursor.bits(1)? != 0;
        let omega_dot_value =
            u32::try_from(cursor.bits(23)?).map_err(|_| Error::Malformed("bit width"))?;
        let iode = cursor.u8()?;
        let idot_sign = cursor.bits(1)? != 0;
        let idot_value =
            u32::try_from(cursor.bits(13)?).map_err(|_| Error::Malformed("bit width"))?;
        let reserved = u32::try_from(cursor.bits(2)?).map_err(|_| Error::Malformed("bit width"))?;
        Ok(Self {
            c_ic,
            omega_0,
            c_is,
            i_0,
            c_rc,
            omega,
            omega_dot_sign,
            omega_dot_value,
            iode,
            idot_sign,
            idot_value,
            reserved,
        })
    }
}
