// Generated by rust/tools/generate_ublox_layouts.py from unchanged system/ubloxd schemas.
// Field tables retain source signedness and alignment, including unused parsed fields.
use crate::{binary::Cursor, Error};
#[derive(Clone, Debug)]
pub struct MonHw {
    pub pin_sel: u32,
    pub pin_bank: u32,
    pub pin_dir: u32,
    pub pin_val: u32,
    pub noise_per_ms: u16,
    pub agc_cnt: u16,
    pub a_status: u8,
    pub a_power: u8,
    pub flags: u8,
    pub used_mask: u32,
    pub jam_ind: u8,
    pub pin_irq: u32,
    pub pull_h: u32,
    pub pull_l: u32,
}
impl MonHw {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let pin_sel = cursor.u32()?;
        let pin_bank = cursor.u32()?;
        let pin_dir = cursor.u32()?;
        let pin_val = cursor.u32()?;
        let noise_per_ms = cursor.u16()?;
        let agc_cnt = cursor.u16()?;
        let a_status = cursor.u8()?;
        let a_power = cursor.u8()?;
        let flags = cursor.u8()?;
        cursor.skip(1)?;
        let used_mask = cursor.u32()?;
        cursor.skip(17)?;
        let jam_ind = cursor.u8()?;
        cursor.skip(2)?;
        let pin_irq = cursor.u32()?;
        let pull_h = cursor.u32()?;
        let pull_l = cursor.u32()?;
        Ok(Self {
            pin_sel,
            pin_bank,
            pin_dir,
            pin_val,
            noise_per_ms,
            agc_cnt,
            a_status,
            a_power,
            flags,
            used_mask,
            jam_ind,
            pin_irq,
            pull_h,
            pull_l,
        })
    }
}
#[derive(Clone, Debug)]
pub struct MonHw2 {
    pub ofs_i: i8,
    pub mag_i: u8,
    pub ofs_q: i8,
    pub mag_q: u8,
    pub cfg_source: u8,
    pub low_lev_cfg: u32,
    pub post_status: u32,
}
impl MonHw2 {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let ofs_i = cursor.i8()?;
        let mag_i = cursor.u8()?;
        let ofs_q = cursor.i8()?;
        let mag_q = cursor.u8()?;
        let cfg_source = cursor.u8()?;
        cursor.skip(3)?;
        let low_lev_cfg = cursor.u32()?;
        cursor.skip(8)?;
        let post_status = cursor.u32()?;
        cursor.skip(4)?;
        Ok(Self {
            ofs_i,
            mag_i,
            ofs_q,
            mag_q,
            cfg_source,
            low_lev_cfg,
            post_status,
        })
    }
}
