// Generated by rust/tools/generate_ublox_layouts.py from unchanged system/ubloxd schemas.
// Field tables retain source signedness and alignment, including unused parsed fields.
use crate::{binary::Cursor, Error};
#[derive(Clone, Debug)]
pub struct NavPvt {
    pub i_tow: u32,
    pub year: u16,
    pub month: u8,
    pub day: u8,
    pub hour: u8,
    pub min: u8,
    pub sec: u8,
    pub valid: u8,
    pub t_acc: u32,
    pub nano: i32,
    pub fix_type: u8,
    pub flags: u8,
    pub flags2: u8,
    pub num_sv: u8,
    pub lon: i32,
    pub lat: i32,
    pub height: i32,
    pub h_msl: i32,
    pub h_acc: u32,
    pub v_acc: u32,
    pub vel_n: i32,
    pub vel_e: i32,
    pub vel_d: i32,
    pub g_speed: i32,
    pub head_mot: i32,
    pub s_acc: i32,
    pub head_acc: u32,
    pub p_dop: u16,
    pub flags3: u8,
    pub head_veh: i32,
    pub mag_dec: i16,
    pub mag_acc: u16,
}
impl NavPvt {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let i_tow = cursor.u32()?;
        let year = cursor.u16()?;
        let month = cursor.u8()?;
        let day = cursor.u8()?;
        let hour = cursor.u8()?;
        let min = cursor.u8()?;
        let sec = cursor.u8()?;
        let valid = cursor.u8()?;
        let t_acc = cursor.u32()?;
        let nano = cursor.i32()?;
        let fix_type = cursor.u8()?;
        let flags = cursor.u8()?;
        let flags2 = cursor.u8()?;
        let num_sv = cursor.u8()?;
        let lon = cursor.i32()?;
        let lat = cursor.i32()?;
        let height = cursor.i32()?;
        let h_msl = cursor.i32()?;
        let h_acc = cursor.u32()?;
        let v_acc = cursor.u32()?;
        let vel_n = cursor.i32()?;
        let vel_e = cursor.i32()?;
        let vel_d = cursor.i32()?;
        let g_speed = cursor.i32()?;
        let head_mot = cursor.i32()?;
        let s_acc = cursor.i32()?;
        let head_acc = cursor.u32()?;
        let p_dop = cursor.u16()?;
        let flags3 = cursor.u8()?;
        cursor.skip(5)?;
        let head_veh = cursor.i32()?;
        let mag_dec = cursor.i16()?;
        let mag_acc = cursor.u16()?;
        Ok(Self {
            i_tow,
            year,
            month,
            day,
            hour,
            min,
            sec,
            valid,
            t_acc,
            nano,
            fix_type,
            flags,
            flags2,
            num_sv,
            lon,
            lat,
            height,
            h_msl,
            h_acc,
            v_acc,
            vel_n,
            vel_e,
            vel_d,
            g_speed,
            head_mot,
            s_acc,
            head_acc,
            p_dop,
            flags3,
            head_veh,
            mag_dec,
            mag_acc,
        })
    }
}
#[derive(Clone, Debug)]
pub struct NavSat {
    pub itow: u32,
    pub version: u8,
    pub num_svs: u8,
}
impl NavSat {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let itow = cursor.u32()?;
        let version = cursor.u8()?;
        let num_svs = cursor.u8()?;
        cursor.skip(2)?;
        Ok(Self {
            itow,
            version,
            num_svs,
        })
    }
}
#[derive(Clone, Debug)]
pub struct Satellite {
    pub gnss_id: u8,
    pub sv_id: u8,
    pub cno: u8,
    pub elev: i8,
    pub azim: i16,
    pub pr_res: i16,
    pub flags: u32,
}
impl Satellite {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let gnss_id = cursor.u8()?;
        let sv_id = cursor.u8()?;
        let cno = cursor.u8()?;
        let elev = cursor.i8()?;
        let azim = cursor.i16()?;
        let pr_res = cursor.i16()?;
        let flags = cursor.u32()?;
        Ok(Self {
            gnss_id,
            sv_id,
            cno,
            elev,
            azim,
            pr_res,
            flags,
        })
    }
}
