// Generated by rust/tools/generate_ublox_layouts.py from unchanged system/ubloxd schemas.
// Field tables retain source signedness and alignment, including unused parsed fields.
use crate::{binary::Cursor, Error};
#[derive(Clone, Debug)]
pub struct Rawx {
    pub rcv_tow: f64,
    pub week: u16,
    pub leap_s: i8,
    pub num_meas: u8,
    pub rec_stat: u8,
}
impl Rawx {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let rcv_tow = cursor.f64()?;
        let week = cursor.u16()?;
        let leap_s = cursor.i8()?;
        let num_meas = cursor.u8()?;
        let rec_stat = cursor.u8()?;
        cursor.skip(3)?;
        Ok(Self {
            rcv_tow,
            week,
            leap_s,
            num_meas,
            rec_stat,
        })
    }
}
#[derive(Clone, Debug)]
pub struct Measurement {
    pub pr_mes: f64,
    pub cp_mes: f64,
    pub do_mes: f32,
    pub gnss_id: u8,
    pub sv_id: u8,
    pub freq_id: u8,
    pub lock_time: u16,
    pub cno: u8,
    pub pr_stdev: u8,
    pub cp_stdev: u8,
    pub do_stdev: u8,
    pub trk_stat: u8,
}
impl Measurement {
    pub fn read(cursor: &mut Cursor<'_>) -> Result<Self, Error> {
        let pr_mes = cursor.f64()?;
        let cp_mes = cursor.f64()?;
        let do_mes = cursor.f32()?;
        let gnss_id = cursor.u8()?;
        let sv_id = cursor.u8()?;
        cursor.skip(1)?;
        let freq_id = cursor.u8()?;
        let lock_time = cursor.u16()?;
        let cno = cursor.u8()?;
        let pr_stdev = cursor.u8()?;
        let cp_stdev = cursor.u8()?;
        let do_stdev = cursor.u8()?;
        let trk_stat = cursor.u8()?;
        cursor.skip(1)?;
        Ok(Self {
            pr_mes,
            cp_mes,
            do_mes,
            gnss_id,
            sv_id,
            freq_id,
            lock_time,
            cno,
            pr_stdev,
            cp_stdev,
            do_stdev,
            trk_stat,
        })
    }
}
