use serde::Serialize;

use super::Register;

#[derive(Debug, Serialize)]
pub struct SensorConfig {
    pub image_sensor: u32,
    pub pixel_size_mm: f32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frame_stride: u32,
    pub frame_offset: u32,
    pub extra_height: u32,
    pub out_scale: i32,
    pub registers_offset: i32,
    pub stats_offset: i32,
    pub hdr_offset: i32,
    pub exposure_time_min: i32,
    pub exposure_time_max: i32,
    pub dc_gain_factor: f32,
    pub dc_gain_min_weight: i32,
    pub dc_gain_max_weight: i32,
    pub dc_gain_on_grey: f32,
    pub dc_gain_off_grey: f32,
    pub ev_scale: f32,
    pub analog_gain_min_idx: i32,
    pub analog_gain_max_idx: i32,
    pub analog_gain_rec_idx: i32,
    pub analog_gain_cost_delta: i32,
    pub analog_gain_cost_low: f32,
    pub analog_gain_cost_high: f32,
    pub target_grey_factor: f32,
    pub min_ev: f32,
    pub max_ev: f32,
    pub data_word: bool,
    pub probe_reg_addr: u32,
    pub probe_expected_data: u32,
    pub bits_per_pixel: u32,
    pub bayer_pattern: u32,
    pub mipi_format: u32,
    pub mclk_frequency: u32,
    pub frame_data_type: u32,
    pub readout_time_ns: u32,
    pub black_level: u32,
    pub sensor_analog_gains: &'static [f32],
    pub start_reg_array: &'static [Register],
    pub init_reg_array: &'static [Register],
    pub color_correct_matrix: &'static [u32],
    pub gamma_lut_rgb: &'static [u32],
    pub linearization_lut: &'static [u32],
    pub linearization_pts: &'static [u32],
    pub vignetting_lut: &'static [u32],
}
