// Generated from unchanged PoseKalman symbolic equations by generate_pose_model.py.
pub fn transition_jacobian(state: &[f64; 18], dt: f64) -> [f64; 324] {
    let mut out = [0.0; 324];
    out[0] = ((-(dt * state[6]).sin() * (dt * state[8]).cos()
        + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
        * (state[0]).cos()
        * (state[1]).cos()
        - (state[0]).sin() * (dt * state[6]).cos() * (dt * state[7]).cos() * (state[1]).cos())
        * (-((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
            + (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
            + ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                - (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[1]).sin()
            - (dt * state[6]).sin() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        .powi(2)
            + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
                - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin()
                + (dt * state[6]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2))
        + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
            + (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[0]).cos()
            * (state[1]).cos()
            - (dt * state[6]).sin() * (state[0]).sin() * (dt * state[7]).cos() * (state[1]).cos())
            * (-((dt * state[6]).sin() * (dt * state[8]).sin()
                + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                    + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
                + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                    + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2)
                + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                    + (dt * state[6]).cos() * (dt * state[8]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                    - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                        - (dt * state[8]).sin() * (dt * state[6]).cos())
                        * (state[1]).sin()
                    + (dt * state[6]).sin()
                        * (dt * state[7]).cos()
                        * (state[0]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[1] = ((-(dt * state[6]).sin() * (dt * state[8]).sin()
        - (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
        * (state[1]).cos()
        - (-(dt * state[6]).sin() * (dt * state[8]).cos()
            + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
            * (state[0]).sin()
            * (state[1]).sin()
        - (state[1]).sin() * (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos())
        * (-((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
            + (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
            + ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                - (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[1]).sin()
            - (dt * state[6]).sin() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        .powi(2)
            + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
                - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin()
                + (dt * state[6]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2))
        + (-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
            * (-((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    + (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).cos()
                - (dt * state[6]).sin()
                    * (state[1]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos())
            / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
                + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                    + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2)
                + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                    + (dt * state[6]).cos() * (dt * state[8]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                    - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                        - (dt * state[8]).sin() * (dt * state[6]).cos())
                        * (state[1]).sin()
                    + (dt * state[6]).sin()
                        * (dt * state[7]).cos()
                        * (state[0]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[6] = (-((dt * state[6]).sin() * (dt * state[8]).sin()
        + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
        * (state[1]).sin()
        + (-(dt * state[6]).sin() * (dt * state[8]).cos()
            + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
        + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        * (dt
            * (dt * state[6]).cos()
            * (dt * state[7]).cos()
            * (state[0]).cos()
            * (state[1]).cos()
            + (-dt * (dt * state[6]).sin() * (dt * state[8]).sin()
                - dt * (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
            + (-dt * (dt * state[6]).sin() * (dt * state[8]).cos()
                + dt * (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos())
        / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        .powi(2)
            + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
                - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin()
                + (dt * state[6]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2))
        + (-((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
            + (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
            + ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                - (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[1]).sin()
            - (dt * state[6]).sin() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
            * (-dt
                * (dt * state[6]).sin()
                * (dt * state[7]).cos()
                * (state[0]).cos()
                * (state[1]).cos()
                + (-dt * (dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                    - dt * (dt * state[6]).cos() * (dt * state[8]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * (dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - dt * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin())
            / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
                + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                    + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2)
                + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                    + (dt * state[6]).cos() * (dt * state[8]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                    - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                        - (dt * state[8]).sin() * (dt * state[6]).cos())
                        * (state[1]).sin()
                    + (dt * state[6]).sin()
                        * (dt * state[7]).cos()
                        * (state[0]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[7] = (-((dt * state[6]).sin() * (dt * state[8]).sin()
        + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
        * (state[1]).sin()
        + (-(dt * state[6]).sin() * (dt * state[8]).cos()
            + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
        + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        * (-dt
            * (dt * state[6]).sin()
            * (dt * state[7]).sin()
            * (state[0]).cos()
            * (state[1]).cos()
            + dt * (dt * state[6]).sin()
                * (dt * state[8]).sin()
                * (state[0]).sin()
                * (dt * state[7]).cos()
                * (state[1]).cos()
            - dt * (dt * state[6]).sin()
                * (state[1]).sin()
                * (dt * state[7]).cos()
                * (dt * state[8]).cos())
        / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        .powi(2)
            + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
                - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin()
                + (dt * state[6]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2))
        + (-((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
            + (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
            + ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                - (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[1]).sin()
            - (dt * state[6]).sin() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
            * (-dt
                * (dt * state[7]).sin()
                * (dt * state[6]).cos()
                * (state[0]).cos()
                * (state[1]).cos()
                + dt * (dt * state[8]).sin()
                    * (state[0]).sin()
                    * (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[1]).cos()
                - dt * (state[1]).sin()
                    * (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos())
            / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
                + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                    + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2)
                + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                    + (dt * state[6]).cos() * (dt * state[8]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                    - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                        - (dt * state[8]).sin() * (dt * state[6]).cos())
                        * (state[1]).sin()
                    + (dt * state[6]).sin()
                        * (dt * state[7]).cos()
                        * (state[0]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[8] = ((dt * (dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
        + dt * (dt * state[6]).cos() * (dt * state[8]).cos())
        * (state[1]).sin()
        + (dt * (dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
            - dt * (dt * state[8]).sin() * (dt * state[6]).cos())
            * (state[0]).sin()
            * (state[1]).cos())
        * (-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
            + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[1]).sin()
            + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
            + (dt * state[6]).cos() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        .powi(2)
            + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
                - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin()
                + (dt * state[6]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2))
        + ((dt * (dt * state[6]).sin() * (dt * state[8]).sin()
            + dt * (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
            * (state[0]).sin()
            * (state[1]).cos()
            + (-dt * (dt * state[6]).sin() * (dt * state[8]).cos()
                + dt * (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                * (state[1]).sin())
            * (-((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                + (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[0]).sin()
                * (state[1]).cos()
                + ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                    - (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[1]).sin()
                - (dt * state[6]).sin()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            / ((-((dt * state[6]).sin() * (dt * state[8]).sin()
                + (dt * state[7]).sin() * (dt * state[6]).cos() * (dt * state[8]).cos())
                * (state[1]).sin()
                + (-(dt * state[6]).sin() * (dt * state[8]).cos()
                    + (dt * state[7]).sin() * (dt * state[8]).sin() * (dt * state[6]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                + (dt * state[6]).cos()
                    * (dt * state[7]).cos()
                    * (state[0]).cos()
                    * (state[1]).cos())
            .powi(2)
                + (((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).sin()
                    + (dt * state[6]).cos() * (dt * state[8]).cos())
                    * (state[0]).sin()
                    * (state[1]).cos()
                    - ((dt * state[6]).sin() * (dt * state[7]).sin() * (dt * state[8]).cos()
                        - (dt * state[8]).sin() * (dt * state[6]).cos())
                        * (state[1]).sin()
                    + (dt * state[6]).sin()
                        * (dt * state[7]).cos()
                        * (state[0]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[18] = (-(dt * state[7]).sin() * (state[0]).sin() * (state[1]).cos()
        - (dt * state[8]).sin() * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
        / (1.0
            - ((dt * state[7]).sin() * (state[0]).cos() * (state[1]).cos()
                - (dt * state[8]).sin()
                    * (state[0]).sin()
                    * (dt * state[7]).cos()
                    * (state[1]).cos()
                + (state[1]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos())
            .powi(2))
        .sqrt();
    out[19] = (-(dt * state[7]).sin() * (state[1]).sin() * (state[0]).cos()
        + (dt * state[8]).sin() * (state[0]).sin() * (state[1]).sin() * (dt * state[7]).cos()
        + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos())
        / (1.0
            - ((dt * state[7]).sin() * (state[0]).cos() * (state[1]).cos()
                - (dt * state[8]).sin()
                    * (state[0]).sin()
                    * (dt * state[7]).cos()
                    * (state[1]).cos()
                + (state[1]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos())
            .powi(2))
        .sqrt();
    out[25] =
        (dt * (dt * state[7]).sin() * (dt * state[8]).sin() * (state[0]).sin() * (state[1]).cos()
            - dt * (dt * state[7]).sin() * (state[1]).sin() * (dt * state[8]).cos()
            + dt * (dt * state[7]).cos() * (state[0]).cos() * (state[1]).cos())
            / (1.0
                - ((dt * state[7]).sin() * (state[0]).cos() * (state[1]).cos()
                    - (dt * state[8]).sin()
                        * (state[0]).sin()
                        * (dt * state[7]).cos()
                        * (state[1]).cos()
                    + (state[1]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos())
                .powi(2))
            .sqrt();
    out[26] = (-dt * (dt * state[8]).sin() * (state[1]).sin() * (dt * state[7]).cos()
        - dt * (state[0]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos())
        / (1.0
            - ((dt * state[7]).sin() * (state[0]).cos() * (state[1]).cos()
                - (dt * state[8]).sin()
                    * (state[0]).sin()
                    * (dt * state[7]).cos()
                    * (state[1]).cos()
                + (state[1]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos())
            .powi(2))
        .sqrt();
    out[36] = (((state[0]).sin() * (state[2]).sin()
        + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
        * (dt * state[8]).sin()
        * (dt * state[7]).cos()
        + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
            - (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).sin())
        * ((-(state[0]).sin() * (state[2]).cos()
            + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).sin()
            - ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                + (state[0]).cos() * (state[2]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            - (state[2]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos())
        / ((-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        .powi(2)
            + (-(-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            .powi(2))
        + ((-(state[0]).sin() * (state[2]).cos()
            + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
            * (dt * state[8]).sin()
            * (dt * state[7]).cos()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                + (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin())
            * (-((state[0]).sin() * (state[2]).sin()
                + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            / ((-((state[0]).sin() * (state[2]).sin()
                + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            .powi(2)
                + (-(-(state[0]).sin() * (state[2]).cos()
                    + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                    * (dt * state[7]).sin()
                    + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                        + (state[0]).cos() * (state[2]).cos())
                        * (dt * state[8]).sin()
                        * (dt * state[7]).cos()
                    + (state[2]).sin()
                        * (dt * state[7]).cos()
                        * (dt * state[8]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[37] = (-((state[0]).sin() * (state[2]).sin()
        + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
        * (dt * state[7]).sin()
        + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
            - (state[2]).sin() * (state[0]).cos())
            * (dt * state[8]).sin()
            * (dt * state[7]).cos()
        + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        * (-(dt * state[7]).sin() * (state[2]).sin() * (state[0]).cos() * (state[1]).cos()
            + (dt * state[8]).sin()
                * (state[0]).sin()
                * (state[2]).sin()
                * (dt * state[7]).cos()
                * (state[1]).cos()
            - (state[1]).sin() * (state[2]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos())
        / ((-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        .powi(2)
            + (-(-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            .powi(2))
        + ((-(state[0]).sin() * (state[2]).cos()
            + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).sin()
            - ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                + (state[0]).cos() * (state[2]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            - (state[2]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos())
            * (-(dt * state[7]).sin() * (state[0]).cos() * (state[1]).cos() * (state[2]).cos()
                + (dt * state[8]).sin()
                    * (state[0]).sin()
                    * (dt * state[7]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos()
                - (state[1]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[2]).cos())
            / ((-((state[0]).sin() * (state[2]).sin()
                + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            .powi(2)
                + (-(-(state[0]).sin() * (state[2]).cos()
                    + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                    * (dt * state[7]).sin()
                    + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                        + (state[0]).cos() * (state[2]).cos())
                        * (dt * state[8]).sin()
                        * (dt * state[7]).cos()
                    + (state[2]).sin()
                        * (dt * state[7]).cos()
                        * (dt * state[8]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[38] = ((-(state[0]).sin() * (state[2]).sin()
        - (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
        * (dt * state[7]).sin()
        + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
            - (state[2]).sin() * (state[0]).cos())
            * (dt * state[8]).sin()
            * (dt * state[7]).cos()
        + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        * (-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        / ((-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        .powi(2)
            + (-(-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            .powi(2))
        + ((-(state[0]).sin() * (state[2]).cos()
            + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).sin()
            + (-(state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                - (state[0]).cos() * (state[2]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            - (state[2]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos())
            * ((-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                - ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                - (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            / ((-((state[0]).sin() * (state[2]).sin()
                + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            .powi(2)
                + (-(-(state[0]).sin() * (state[2]).cos()
                    + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                    * (dt * state[7]).sin()
                    + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                        + (state[0]).cos() * (state[2]).cos())
                        * (dt * state[8]).sin()
                        * (dt * state[7]).cos()
                    + (state[2]).sin()
                        * (dt * state[7]).cos()
                        * (dt * state[8]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[43] = (-((state[0]).sin() * (state[2]).sin()
        + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
        * (dt * state[7]).sin()
        + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
            - (state[2]).sin() * (state[0]).cos())
            * (dt * state[8]).sin()
            * (dt * state[7]).cos()
        + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        * (dt
            * ((state[0]).sin() * (state[2]).cos()
                - (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).cos()
            - dt * ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                + (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                * (dt * state[8]).sin()
            - dt * (dt * state[7]).sin()
                * (state[2]).sin()
                * (dt * state[8]).cos()
                * (state[1]).cos())
        / ((-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        .powi(2)
            + (-(-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            .powi(2))
        + ((-(state[0]).sin() * (state[2]).cos()
            + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).sin()
            - ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                + (state[0]).cos() * (state[2]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            - (state[2]).sin() * (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos())
            * (dt
                * (-(state[0]).sin() * (state[2]).sin()
                    - (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).cos()
                - dt * ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[7]).sin()
                    * (dt * state[8]).sin()
                - dt * (dt * state[7]).sin()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            / ((-((state[0]).sin() * (state[2]).sin()
                + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            .powi(2)
                + (-(-(state[0]).sin() * (state[2]).cos()
                    + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                    * (dt * state[7]).sin()
                    + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                        + (state[0]).cos() * (state[2]).cos())
                        * (dt * state[8]).sin()
                        * (dt * state[7]).cos()
                    + (state[2]).sin()
                        * (dt * state[7]).cos()
                        * (dt * state[8]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[44] = (dt
        * ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
            + (state[0]).cos() * (state[2]).cos())
        * (dt * state[7]).cos()
        * (dt * state[8]).cos()
        - dt * (dt * state[8]).sin() * (state[2]).sin() * (dt * state[7]).cos() * (state[1]).cos())
        * (-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        / ((-((state[0]).sin() * (state[2]).sin()
            + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
            * (dt * state[7]).sin()
            + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
                * (dt * state[8]).sin()
                * (dt * state[7]).cos()
            + (dt * state[7]).cos() * (dt * state[8]).cos() * (state[1]).cos() * (state[2]).cos())
        .powi(2)
            + (-(-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            .powi(2))
        + (dt
            * ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                - (state[2]).sin() * (state[0]).cos())
            * (dt * state[7]).cos()
            * (dt * state[8]).cos()
            - dt * (dt * state[8]).sin()
                * (dt * state[7]).cos()
                * (state[1]).cos()
                * (state[2]).cos())
            * ((-(state[0]).sin() * (state[2]).cos()
                + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                * (dt * state[7]).sin()
                - ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                    + (state[0]).cos() * (state[2]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                - (state[2]).sin()
                    * (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos())
            / ((-((state[0]).sin() * (state[2]).sin()
                + (state[1]).sin() * (state[0]).cos() * (state[2]).cos())
                * (dt * state[7]).sin()
                + ((state[0]).sin() * (state[1]).sin() * (state[2]).cos()
                    - (state[2]).sin() * (state[0]).cos())
                    * (dt * state[8]).sin()
                    * (dt * state[7]).cos()
                + (dt * state[7]).cos()
                    * (dt * state[8]).cos()
                    * (state[1]).cos()
                    * (state[2]).cos())
            .powi(2)
                + (-(-(state[0]).sin() * (state[2]).cos()
                    + (state[1]).sin() * (state[2]).sin() * (state[0]).cos())
                    * (dt * state[7]).sin()
                    + ((state[0]).sin() * (state[1]).sin() * (state[2]).sin()
                        + (state[0]).cos() * (state[2]).cos())
                        * (dt * state[8]).sin()
                        * (dt * state[7]).cos()
                    + (state[2]).sin()
                        * (dt * state[7]).cos()
                        * (dt * state[8]).cos()
                        * (state[1]).cos())
                .powi(2));
    out[57] = 1.0;
    out[66] = dt;
    out[76] = 1.0;
    out[85] = dt;
    out[95] = 1.0;
    out[104] = dt;
    out[114] = 1.0;
    out[133] = 1.0;
    out[152] = 1.0;
    out[171] = 1.0;
    out[190] = 1.0;
    out[209] = 1.0;
    out[228] = 1.0;
    out[247] = 1.0;
    out[266] = 1.0;
    out[285] = 1.0;
    out[304] = 1.0;
    out[323] = 1.0;
    out
}
